image: python:3.8

before_script:
  - python -V
  - pip install --upgrade pip

stages:
  - test
  - style
  - deploy

test:
  stage: test
  services:
    - name: postgres:13.0
      alias: db
  variables:
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: 'postgres'
    POSTGRES_DB: 'test'
    DEBUG: "True"
    TEST_MODE: "True"
  before_script:
    - pip install -r requirements.txt
  script:
    - coverage run -m pytest --disable-warnings
    - coverage report --omit=app/test_app.py -m
    - coverage html --omit=app/test_app.py
    - mkdir public
    - mv htmlcov public/coverage
  artifacts:
    paths:
      - public/coverage
  only:
    - master

pylint:
  stage: style
  before_script:
    - pip install -r requirements.txt
    - pip install pylint==2.6.0
    - pip install pylint-json2html==0.2.0
    - pip install anybadge==1.7.0
  script:
    ./pylint_runner.sh
  artifacts:
    paths:
      - public/pylint.svg
      - public/pylint.html
  only:
    - master


pages:
  stage: deploy
  script:
  - echo 'Publish pages data'
  artifacts:
    paths:
    - public
  only:
  - master
