version: '3'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=candy_delivery_db 
    ports:
      - 5432:5432
    restart: always

  api:
    build: ./
    command: ./docker-entrypoint.sh
    volumes: 
      - ./:/root/app 
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
    postgres_data:
