version: '3'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always

  api:
    build: ./
    command: ./docker-entrypoint.sh
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db
